var data = [{id: 0, text: "numero 0", temperatura: 25, codigo: "COD 0"}, 
{id: 1, text: "numero 1", temperatura: 10, codigo: "COD 1"},
{id: 2, text: "numero 2", temperatura: 10, codigo: "COD 2"},
{id: 3, text: "numero 3", temperatura: 10, codigo: "COD 3"},
{id: 4, text: "numero 4", temperatura: 10, codigo: "COD 4"},
{id: 5, text: "numero 5", temperatura: 10, codigo: "COD 5"},
{id: 6, text: "numero 6", temperatura: 10, codigo: "COD 6"},
{id: 7, text: "numero 7", temperatura: 10, codigo: "COD 7"},
{id: 8, text: "numero 8", temperatura: 10, codigo: "COD 8"},
{id: 9, text: "numero 9", temperatura: 10, codigo: "COD 9"},
{id: 10, text: "numero 10", temperatura: 10, codigo: "COD 10"},
{id: 11, text: "numero 11", temperatura: 10, codigo: "COD 11"},
{id: 12, text: "numero 12", temperatura: 10, codigo: "COD 12"},
{id: 13, text: "numero 13", temperatura: 10, codigo: "COD 13"},
{id: 14, text: "numero 14", temperatura: 10, codigo: "COD 14"},
{id: 15, text: "numero 15", temperatura: 10, codigo: "COD 15"},                        
];  
